site_name: Oppkey RICOH Viewer Demo
site_url: https://theta360developers.github.io/ricoh-viewer
site_author: Oppkey

theme:
  name: material
  # features:
  #   - navigation.instant
  logo: images/oppkey_logo.jpg
  favicon: images/oppkey_logo.jpg
repo_name: git@github.com:theta360developers/ricoh-viewer.git

nav:
  - Home: index.md
  - Demo Overview: overview.md
  - Cloud: cloud.md
  - Features: features.md
  - Structure: structure.md
  - Contact: contact.md

plugins:
  - search

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
